default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port:     <%= ENV.fetch("DATABASE_PORT") { '5432' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: 'app_development'

test:
  <<: *default
  database: 'app_test'

staging:
  <<: *default
  database: 'app_staging'

production:
  <<: *default
  database: 'app_production'
