version: '3.8'

services:
  web:
    image: "${APP_NAME}_web_production:latest"
    build:
      context: .
      target: app-for-production
      args:
        bundle_jobs: 8
        bundle_without: development:test