version: '3.8'

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_volume:/var/lib/postgresql/data:cached

  web:
    image: &web_image "${APP_NAME}_web:latest"
    build:
      context: .
      target: app-for-development-and-test
      args:
        bundle_jobs: 8
        bundle_without: production
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes: &web_volumes
      - .:/app:cached
      - gem_volume:/usr/local/bundle
      - /app/log
      - /app/tmp
      - /app/.git
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  ### After you configure sidekiq settings, disable the comments bellow.
  # redis:
  #   image: redis:alpine
  #   volumes:
  #     - redis_volume:/data:cached
  #   ports:
  #     - 6379:6379

  # sidekiq:
  #   image: *web_image
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   env_file:
  #     .env
  #   volumes: *web_volumes
  #   depends_on:
  #     - db
  #     - redis

  # minio:
  #   image: minio/minio:latest
  #   entrypoint: sh
  #   command: -c 'mkdir -p /export/${MINIO_BUCKET_FOR_DEVELOPMENT} && mkdir -p /export/${MINIO_BUCKET_FOR_TEST} && minio server /export'
  #   env_file:
  #     - .env
  #   volumes:
  #     - minio_volume:/data:cached
  #   ports:
  #     - 9000:9000

volumes:
  db_volume:
  gem_volume:
  redis_volume:
  minio_volume:

