version: '3.8'

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    image: "${APP_NAME}_web"
    build:
      context: .
      target: app-for-development-and-test
      args:
        bundle_jobs: 8
        bundle_without: staging:production
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - gems:/usr/local/bundle
      - tmp:/app/tmp
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  ### After you configure sidekiq settings, disable the comments bellow.
  # redis:
  #   image: redis:6.2.6-alpine
  #   volumes:
  #     - redis:/data
  #   ports:
  #     - 6379:6379

  # sidekiq:
  #   image: "${APP_NAME}_web"
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app:cached
  #     - gems:/usr/local/bundle
  #     - tmp:/app/tmp
  #   depends_on:
  #     - db
  #     - redis

  minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /export/${MINIO_BUCKET_FOR_DEVELOPMENT} && mkdir -p /export/${MINIO_BUCKET_FOR_TEST} && minio server /export'
    env_file:
      - .env
    volumes:
      - minio:/data
    ports:
      - 9000:9000

volumes:
  gems:
  tmp:
  redis:
  minio:

